# [np] sum

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [7]:
x = np.arange(60).reshape(3, 4, 5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [16]:
# axis=0でのsum
x_0 = x.sum(axis=0)
print('x_0', x_0)
print('{} ---> {}'.format(x.shape, x_0.shape))

x_0 [[ 60  63  66  69  72]
 [ 75  78  81  84  87]
 [ 90  93  96  99 102]
 [105 108 111 114 117]]
(3, 4, 5) ---> (4, 5)


In [17]:
# axis=0でのsum
x_0 = x.sum(axis=0, keepdims=True)
print('x_0', x_0)
print('{} ---> {}'.format(x.shape, x_0.shape))

x_0 [[[ 60  63  66  69  72]
  [ 75  78  81  84  87]
  [ 90  93  96  99 102]
  [105 108 111 114 117]]]
(3, 4, 5) ---> (1, 4, 5)


In [14]:
# axis=0でのsum
x_1 = x.sum(axis=1)
print('x_1', x_1)
print('{} ---> {}'.format(x.shape, x_1.shape))

x_1 [[ 30  34  38  42  46]
 [110 114 118 122 126]
 [190 194 198 202 206]]
(3, 4, 5) ---> (3, 5)
