In [10]:
import numpy as np

In [30]:
# 配列を作る
# np.array(array)
a = np.array([[1, 2, 3], [4, 5, 6]])

# 配列の情報を取得する
print('array: ', a)
print('a.shape: ', a.shape)
print('a.size: ', a.size)
print('a.sum: ', a.sum())
print('a.ndarray', a.ndarray)

# 関数化
def info(array):
    print('array: ', array)
    print('shape: ', array.shape)
    print('size: ', array.size)
    print('sum: ', array.sum())

array:  [[1 2 3]
 [4 5 6]]
a.shape:  (2, 3)
a.size:  6
a.sum:  21


AttributeError: 'numpy.ndarray' object has no attribute 'ndarray'

In [23]:
# 要素がゼロの配列
a = np.zeros(4)
info(a)

a = np.zeros((3, 128, 128))
info(a)

array:  [0. 0. 0. 0.]
shape:  (4,)
size:  4
sum:  0.0
array:  [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
shape:  (3, 128, 128)
size:  49152
sum:  0.0


In [24]:
# 配列を作成する
# np.arange(num) out: arary([...num])
b = np.arange(5)

info(b)

array:  [0 1 2 3 4]
shape:  (5,)
size:  5
sum:  10


In [25]:
# np.arange(start, end, linspace)
c = np.arange(10, 20, 2)
info(c)

array:  [10 12 14 16 18]
shape:  (5,)
size:  5
sum:  70


In [26]:
# np.linspace(start, end, num_divide)
d = np.linspace(1, 10, 10)
info(d)

array:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
shape:  (10,)
size:  10
sum:  55.0


In [27]:
# 配列の形を変更する
# np.reshape(num_cols, num_rows)
e = np.linspace(1, 15, 15).reshape(5, 3)
info(e)

array:  [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
shape:  (5, 3)
size:  15
sum:  120.0


In [28]:
# 要素の数が同じであれば、reshapeできる
f = e.reshape(3, 5)
info(f)

g = np.zeros((128, 128)).reshape(128 * 128)
info(g)

array:  [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
shape:  (3, 5)
size:  15
sum:  120.0
array:  [0. 0. 0. ... 0. 0. 0.]
shape:  (16384,)
size:  16384
sum:  0.0


In [31]:
# np.transpose() np.TでもOK
h = np.arange(10).reshape(2, 5)
info(h)
i = h.T
info(i)

array:  [[0 1 2 3 4]
 [5 6 7 8 9]]
shape:  (2, 5)
size:  10
sum:  45
array:  [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
shape:  (5, 2)
size:  10
sum:  45
